/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container": "#e5eeff",
        "primary-fixed": "#e2dfff",
        "on-error": "#ffffff",
        "inverse-primary": "#c1c1ff",
        "on-secondary-fixed": "#410004",
        "on-primary-container": "#b2b2ff",
        "on-secondary": "#ffffff",
        "surface": "#FAFAFA",
        "surface-container-highest": "#d3e4fe",
        "on-primary": "#ffffff",
        "surface-bright": "#f8f9ff",
        "on-secondary-fixed-variant": "#930013",
        "on-surface": "#0b1c30",
        "secondary-fixed-dim": "#ffb3ad",
        "on-primary-fixed": "#0c0367",
        "on-error-container": "#93000a",
        "on-tertiary-fixed": "#2e1500",
        "outline-variant": "#c7c5d3",
        "on-tertiary-container": "#f6a967",
        "primary": "#27267d",
        "surface-container-low": "#eff4ff",
        "on-tertiary-fixed-variant": "#6d3900",
        "surface-variant": "#d3e4fe",
        "trust-slate": "#E2E8F0",
        "legal-ink": "#1E1B4B",
        "tertiary-fixed-dim": "#ffb77c",
        "verified-gold": "#D4AF37",
        "error-container": "#ffdad6",
        "surface-dim": "#cbdbf5",
        "background": "#f8f9ff",
        "on-secondary-container": "#fffbff",
        "surface-tint": "#5454ab",
        "primary-container": "#3f3f95",
        "secondary-fixed": "#ffdad7",
        "tertiary-container": "#723c00",
        "on-background": "#0b1c30",
        "inverse-on-surface": "#eaf1ff",
        "on-primary-fixed-variant": "#3c3c92",
        "secondary": "#bb001b",
        "inverse-surface": "#213145",
        "primary-fixed-dim": "#c1c1ff",
        "secondary-container": "#e02830",
        "tertiary-fixed": "#ffdcc2",
        "surface-container-lowest": "#ffffff",
        "outline": "#777683",
        "error": "#ba1a1a",
        "on-surface-variant": "#464651",
        "on-tertiary": "#ffffff",
        "tertiary": "#512900",
        "surface-container-high": "#dce9ff"
      },
      borderRadius: {
        DEFAULT: "4px",
        lg: "4px",
        xl: "4px",
        full: "9999px"
      },
      fontFamily: {
        "display-lg": ["Montserrat"],
        "label-sm": ["Inter"],
        "body-md": ["Inter"],
        "headline-lg": ["Montserrat"],
        "headline-md": ["Montserrat"],
        "headline-lg-mobile": ["Montserrat"],
        "body-lg": ["Inter"],
        "label-md": ["Inter"]
      },
      fontSize: {
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "500"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "fontWeight": "700"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "headline-lg-mobile": ["28px", {"lineHeight": "34px", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "600"}]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
